"""Tests for generate_cti_report tool helpers in tools_workflow.py."""
import inspect
import unittest

from arkana.mcp.tools_workflow import (
    _format_file_size,
    _get_executive_summary,
    _build_cti_markdown,
    _build_cti_json,
    generate_cti_report,
)


class TestFormatFileSize(unittest.TestCase):
    """Tests for _format_file_size helper."""

    def test_bytes(self):
        result = _format_file_size(500)
        self.assertEqual(result, "500 bytes")

    def test_kilobytes(self):
        result = _format_file_size(2048)
        self.assertIn("KB", result)
        self.assertIn("2,048", result)

    def test_megabytes(self):
        result = _format_file_size(5_242_880)
        self.assertIn("MB", result)
        self.assertIn("5,242,880", result)

    def test_zero(self):
        result = _format_file_size(0)
        self.assertEqual(result, "0 bytes")

    def test_exactly_1kb(self):
        result = _format_file_size(1024)
        self.assertIn("KB", result)

    def test_exactly_1mb(self):
        result = _format_file_size(1_048_576)
        self.assertIn("MB", result)


class TestGetExecutiveSummary(unittest.TestCase):
    """Tests for _get_executive_summary helper."""

    def test_conclusion_note_preferred(self):
        notes = [
            {"category": "general", "content": "General note"},
            {"category": "conclusion", "content": "Final verdict"},
            {"category": "hypothesis", "content": "Initial hypothesis"},
        ]
        result = _get_executive_summary(notes, {})
        self.assertEqual(result, "Final verdict")

    def test_hypothesis_fallback(self):
        notes = [
            {"category": "general", "content": "General note"},
            {"category": "hypothesis", "content": "Initial hypothesis"},
        ]
        result = _get_executive_summary(notes, {})
        self.assertEqual(result, "Initial hypothesis")

    def test_triage_fallback(self):
        notes = [{"category": "general", "content": "General note"}]
        triage = {
            "risk_level": "HIGH",
            "risk_score": 75,
            "suspicious_capabilities": [{"cap": "a"}],
            "suspicious_imports": [
                {"function": "CreateRemoteThread", "risk": "HIGH"},
            ],
        }
        result = _get_executive_summary(notes, triage)
        self.assertIn("HIGH", result)
        self.assertIn("75", result)

    def test_triage_packed(self):
        notes = []
        triage = {
            "risk_level": "MEDIUM",
            "risk_score": 50,
            "packing_assessment": {"likely_packed": True, "packer_name": "UPX"},
        }
        result = _get_executive_summary(notes, triage)
        self.assertIn("packed", result)
        self.assertIn("UPX", result)

    def test_no_data(self):
        result = _get_executive_summary([], {})
        self.assertIn("No analysis data", result)

    def test_escape_sequences(self):
        notes = [
            {"category": "conclusion", "content": "Line1\\nLine2\\tTabbed"},
        ]
        result = _get_executive_summary(notes, {})
        self.assertIn("Line1\nLine2\tTabbed", result)


class TestBuildCtiMarkdown(unittest.TestCase):
    """Tests for _build_cti_markdown helper."""

    def _minimal_pe_data(self):
        return {
            "file_hashes": {
                "sha256": "abc123" * 10 + "abcd",
                "md5": "def456" * 5 + "de",
                "sha1": "ghi789" * 6 + "ghij",
            },
            "mode": "pe32",
            "nt_headers": {
                "file_header": {
                    "machine": "AMD64",
                    "time_date_stamp": "2024-01-15 12:00:00",
                },
            },
        }

    def test_basic_markdown_structure(self):
        pe = self._minimal_pe_data()
        result = _build_cti_markdown(pe, {}, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("# Malware Analysis Report", result)
        self.assertIn("## Executive Summary", result)
        self.assertIn("## Sample Information", result)
        self.assertIn("## MITRE ATT&CK Mapping", result)
        self.assertIn("## Indicators of Compromise", result)
        self.assertIn("Generated by Arkana", result)

    def test_hashes_in_table(self):
        pe = self._minimal_pe_data()
        result = _build_cti_markdown(pe, {}, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("abc123", result)
        self.assertIn("def456", result)
        self.assertIn("ghi789", result)

    def test_mitre_techniques_rendered(self):
        pe = self._minimal_pe_data()
        mitre = {
            "techniques": [
                {
                    "id": "T1055",
                    "name": "Process Injection",
                    "tactic": "defense-evasion",
                    "confidence": 80,
                    "sources": [{"type": "import", "function": "WriteProcessMemory"}],
                },
            ],
            "tactics_covered": 1,
            "tactics_total": 14,
        }
        result = _build_cti_markdown(pe, {}, None, None, mitre, None, [], "/tmp/test.exe")
        self.assertIn("T1055", result)
        self.assertIn("Process Injection", result)
        self.assertIn("Defense Evasion", result)

    def test_iocs_from_cached(self):
        pe = self._minimal_pe_data()
        iocs = {
            "iocs": {
                "ipv4": ["192.168.1.1", "10.0.0.1"],
                "domains": ["evil.com"],
                "urls": ["http://evil.com/payload"],
            },
        }
        result = _build_cti_markdown(pe, {}, None, None, None, iocs, [], "/tmp/test.exe")
        self.assertIn("192.168.1.1", result)
        self.assertIn("evil.com", result)
        self.assertIn("Network Indicators", result)

    def test_iocs_fallback_to_triage(self):
        pe = self._minimal_pe_data()
        triage = {
            "network_iocs": {
                "ip_addresses": ["1.2.3.4"],
                "domains": [],
                "urls": [],
            },
        }
        result = _build_cti_markdown(pe, triage, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("1.2.3.4", result)

    def test_similarity_hashes_in_table(self):
        pe = self._minimal_pe_data()
        sim = {
            "ssdeep": "3:abc:def",
            "tlsh": "T1AABBCC",
            "imphash": "aabb1122",
        }
        result = _build_cti_markdown(pe, {}, None, sim, None, None, [], "/tmp/test.exe")
        self.assertIn("3:abc:def", result)
        self.assertIn("T1AABBCC", result)
        self.assertIn("aabb1122", result)

    def test_classification_section(self):
        pe = self._minimal_pe_data()
        cls = {
            "primary_type": "Trojan Dropper",
            "classifications": ["Trojan Dropper", "Network Client"],
            "evidence": ["Imports WriteProcessMemory", "Contains URL strings"],
        }
        result = _build_cti_markdown(pe, {}, cls, None, None, None, [], "/tmp/test.exe")
        self.assertIn("## Classification", result)
        self.assertIn("Trojan Dropper", result)
        self.assertIn("Network Client", result)

    def test_anti_analysis_section(self):
        pe = self._minimal_pe_data()
        triage = {
            "packing_assessment": {"likely_packed": True, "packer_name": "UPX"},
            "suspicious_imports": [
                {"function": "IsDebuggerPresent", "dll": "kernel32.dll", "risk": "HIGH"},
            ],
            "suspicious_capabilities": [
                {"capability": "check for debugger", "namespace": "anti-analysis/anti-debugging", "severity": "HIGH"},
            ],
        }
        result = _build_cti_markdown(pe, triage, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("## Anti-Analysis Techniques", result)
        self.assertIn("UPX", result)
        self.assertIn("IsDebuggerPresent", result)

    def test_analyst_notes_section(self):
        pe = self._minimal_pe_data()
        notes = [
            {"category": "hypothesis", "content": "Likely dropper", "created_at": "2024-01-15T12:00:00"},
            {"category": "general", "content": "Imports suspicious APIs"},
        ]
        result = _build_cti_markdown(pe, {}, None, None, None, None, notes, "/tmp/test.exe")
        self.assertIn("## Analyst Notes", result)
        self.assertIn("Likely dropper", result)

    def test_capabilities_from_capa(self):
        pe = self._minimal_pe_data()
        pe["capa_analysis"] = {
            "results": {
                "rules": {
                    "create file": {
                        "meta": {"name": "create file", "namespace": "host-interaction/file-system"},
                    },
                },
            },
        }
        result = _build_cti_markdown(pe, {}, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("## Capabilities", result)
        self.assertIn("create file", result)

    def test_capabilities_fallback_to_triage(self):
        pe = self._minimal_pe_data()
        triage = {
            "suspicious_capabilities": [
                {"capability": "encrypt data", "namespace": "data-manipulation/encryption", "severity": "MEDIUM"},
            ],
        }
        result = _build_cti_markdown(pe, triage, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("## Capabilities", result)
        self.assertIn("encrypt data", result)

    def test_detection_rules_yara(self):
        pe = self._minimal_pe_data()
        triage = {
            "yara_matches": [
                {"rule": "suspicious_packer", "description": "Detects packed binaries"},
            ],
        }
        result = _build_cti_markdown(pe, triage, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("## Detection Rules", result)
        self.assertIn("suspicious_packer", result)

    def test_host_indicators(self):
        pe = self._minimal_pe_data()
        iocs = {
            "iocs": {
                "registry_keys": [r"HKLM\Software\Evil"],
                "mutexes": [r"Global\EvilMutex"],
                "file_paths": [r"C:\Windows\Temp\evil.dll"],
            },
        }
        result = _build_cti_markdown(pe, {}, None, None, None, iocs, [], "/tmp/test.exe")
        self.assertIn("Host Indicators", result)
        self.assertIn("EvilMutex", result)

    def test_graceful_missing_data(self):
        """All sections handle missing data gracefully."""
        result = _build_cti_markdown({}, {}, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("# Malware Analysis Report", result)
        self.assertIn("N/A", result)
        self.assertIn("Generated by Arkana", result)


class TestBuildCtiJson(unittest.TestCase):
    """Tests for _build_cti_json helper."""

    def _minimal_pe_data(self):
        return {
            "file_hashes": {
                "sha256": "abc123",
                "md5": "def456",
                "sha1": "ghi789",
            },
            "mode": "pe32",
            "nt_headers": {"file_header": {"machine": "AMD64"}},
        }

    def test_basic_structure(self):
        pe = self._minimal_pe_data()
        result = _build_cti_json(pe, {}, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("generated_at", result)
        self.assertIn("executive_summary", result)
        self.assertIn("sample_info", result)

    def test_sample_info_fields(self):
        pe = self._minimal_pe_data()
        result = _build_cti_json(pe, {}, None, None, None, None, [], "/tmp/test.exe")
        info = result["sample_info"]
        self.assertEqual(info["sha256"], "abc123")
        self.assertEqual(info["md5"], "def456")
        self.assertEqual(info["sha1"], "ghi789")
        self.assertEqual(info["filename"], "test.exe")

    def test_classification_overrides_file_type(self):
        pe = self._minimal_pe_data()
        cls = {"primary_type": "Trojan", "classifications": ["Trojan"]}
        result = _build_cti_json(pe, {}, cls, None, None, None, [], "/tmp/test.exe")
        self.assertEqual(result["sample_info"]["file_type"], "Trojan")

    def test_mitre_techniques(self):
        pe = self._minimal_pe_data()
        mitre = {
            "techniques": [{"id": "T1055", "name": "Process Injection", "tactic": "defense-evasion", "confidence": 80}],
            "tactics_covered": 1,
        }
        result = _build_cti_json(pe, {}, None, None, mitre, None, [], "/tmp/test.exe")
        self.assertIn("mitre_attack", result)
        self.assertEqual(result["mitre_attack"]["technique_count"], 1)

    def test_iocs_from_cached(self):
        pe = self._minimal_pe_data()
        iocs = {"iocs": {"ipv4": ["1.2.3.4"]}, "total_iocs": 1}
        result = _build_cti_json(pe, {}, None, None, None, iocs, [], "/tmp/test.exe")
        self.assertIn("iocs", result)
        self.assertEqual(result["ioc_total"], 1)

    def test_iocs_fallback_to_triage(self):
        pe = self._minimal_pe_data()
        triage = {"network_iocs": {"ip_addresses": ["5.6.7.8"], "domains": [], "urls": [], "registry_keys": []}}
        result = _build_cti_json(pe, triage, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("iocs", result)
        self.assertIn("5.6.7.8", result["iocs"]["ipv4"])

    def test_risk_assessment(self):
        pe = self._minimal_pe_data()
        triage = {
            "risk_level": "CRITICAL",
            "risk_score": 95,
            "packing_assessment": {"likely_packed": True, "packer_name": "Themida"},
        }
        result = _build_cti_json(pe, triage, None, None, None, None, [], "/tmp/test.exe")
        self.assertEqual(result["risk_assessment"]["risk_level"], "CRITICAL")
        self.assertEqual(result["risk_assessment"]["risk_score"], 95)
        self.assertTrue(result["risk_assessment"]["packed"])
        self.assertEqual(result["risk_assessment"]["packer"], "Themida")

    def test_analyst_notes(self):
        pe = self._minimal_pe_data()
        notes = [
            {"category": "hypothesis", "content": "Test hypothesis", "created_at": "2024-01-15"},
            {"category": "function", "content": "Should be excluded"},
        ]
        result = _build_cti_json(pe, {}, None, None, None, None, notes, "/tmp/test.exe")
        self.assertIn("analyst_notes", result)
        self.assertEqual(len(result["analyst_notes"]), 1)
        self.assertEqual(result["analyst_notes"][0]["content"], "Test hypothesis")

    def test_capabilities_from_capa(self):
        pe = self._minimal_pe_data()
        pe["capa_analysis"] = {
            "results": {
                "rules": {
                    "encrypt data": {
                        "meta": {"name": "encrypt data", "namespace": "data-manipulation/encryption"},
                    },
                },
            },
        }
        result = _build_cti_json(pe, {}, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("capabilities", result)
        self.assertEqual(result["capabilities"][0]["name"], "encrypt data")

    def test_similarity_hashes(self):
        pe = self._minimal_pe_data()
        sim = {"ssdeep": "abc", "tlsh": "def", "imphash": "ghi"}
        result = _build_cti_json(pe, {}, None, sim, None, None, [], "/tmp/test.exe")
        self.assertEqual(result["sample_info"]["ssdeep"], "abc")
        self.assertEqual(result["sample_info"]["tlsh"], "def")
        self.assertEqual(result["sample_info"]["imphash"], "ghi")

    def test_graceful_empty_data(self):
        result = _build_cti_json({}, {}, None, None, None, None, [], "/tmp/test.exe")
        self.assertIn("generated_at", result)
        self.assertIn("sample_info", result)


class TestGenerateCtiReportSignature(unittest.TestCase):
    """Verify generate_cti_report has correct parameter signature."""

    def test_has_format_param(self):
        inner = getattr(generate_cti_report, "__wrapped__", generate_cti_report)
        sig = inspect.signature(inner)
        self.assertIn("format", sig.parameters)
        self.assertEqual(sig.parameters["format"].default, "markdown")

    def test_has_output_path_param(self):
        inner = getattr(generate_cti_report, "__wrapped__", generate_cti_report)
        sig = inspect.signature(inner)
        self.assertIn("output_path", sig.parameters)
        self.assertEqual(sig.parameters["output_path"].default, "")

    def test_has_ctx_param(self):
        inner = getattr(generate_cti_report, "__wrapped__", generate_cti_report)
        sig = inspect.signature(inner)
        self.assertIn("ctx", sig.parameters)


if __name__ == "__main__":
    unittest.main()
